### PR TITLE
main.css: Change services font size to match with quotes

### PR DESCRIPTION
**Pull request by hemangsk**

### CODE REVIEW

**Comment by sils** [comment]
https://github.com/viper-development/viper-development.github.io/pull/58/commits/a47752ee9711e1aff2d1004bb093cf0f4e7f2ab0 is ready

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
no rultor o nthis repo, forgot

**Comment by hemangsk** [comment]
woah! how did that happen! 🎉

**Comment by hemangsk** [comment]
so rultor is everywhere 🎢

**Pull request merged**
